-- ============================================================================
-- Jubla Triengen CMS - seed data
-- Generated from the legacy static content modules (src/data/*).
-- ============================================================================
BEGIN;

INSERT INTO pages (key, route, template, hero, description, meta, sort_order, published) VALUES
  ($seed$home$seed$, $seed$/$seed$, $seed$home$seed$, NULL, NULL, $seed${}$seed$::jsonb, 1, true),
  ($seed$about$seed$, $seed$/über-uns$seed$, $seed$about$seed$, $seed${"image":"https://media.jubla-triengen.ch/about-header.jpg","title":"Über die Jubla","subtitle":"Gemeinschaft, Abenteuer und unvergessliche Momente"}$seed$::jsonb, NULL, $seed${}$seed$::jsonb, 2, true),
  ($seed$leaders$seed$, $seed$/leiter$seed$, $seed$leaders$seed$, $seed${"image":"https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80","title":"Unser Leitungsteam","subtitle":"Gemeinsam für unvergessliche Erlebnisse"}$seed$::jsonb, $seed${"title":"Wer wir sind","description":"Das Herzstück der Jubla Triengen sind unsere freiwilligen Leiterinnen und Leiter. Sie planen und führen Gruppenstunden, Scharanlässe und Lager durch - mit viel Herzblut und ehrenamtlichem Engagement."}$seed$::jsonb, $seed${}$seed$::jsonb, 3, true),
  ($seed$leader_detail$seed$, $seed$/leiter/:id$seed$, $seed$leader_detail$seed$, NULL, NULL, $seed${"notFoundTitle":"Leiter nicht gefunden","backLabel":"Zurück zur Übersicht","contactTitle":"Kontakt","noContactText":"Keine Kontaktdaten öffentlich","birthdayLabel":"Geburtstag","professionLabel":"Beruf","coursesLabel":"J+S Kurse","rolesLabel":"Ämtli in der Schar","aboutLabel":"Über mich","hobbiesLabel":"Freizeit","highlightLabel":"Jubla Highlight"}$seed$::jsonb, 4, true),
  ($seed$activities$seed$, $seed$/anlässe$seed$, $seed$activities$seed$, $seed${"image":"https://images.unsplash.com/photo-1502086223501-681a6a508d52?auto=format&fit=crop&q=80","title":"Jahres Programm"}$seed$::jsonb, $seed${"title":"Unsere Aktivitäten","description":"Entdecke unser vielfältiges Jahresprogramm voller spannender Aktivitäten, die für jedes Alter und Interesse etwas bieten."}$seed$::jsonb, $seed${}$seed$::jsonb, 5, true),
  ($seed$activity_detail$seed$, $seed$/anlässe/:id$seed$, $seed$activity_detail$seed$, NULL, NULL, $seed${"notFoundTitle":"Aktivität nicht gefunden","backLabel":"Zurück zur Übersicht","downloadsTitle":"Downloads & Infos","downloadLabel":"Download"}$seed$::jsonb, 6, true),
  ($seed$offerings$seed$, $seed$/angebote$seed$, $seed$offerings$seed$, $seed${"image":"https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80","title":"Unsere Angebote","subtitle":"Entdecke die Vielfalt der Jubla Triengen"}$seed$::jsonb, $seed${"title":"Was wir bieten","description":"Die Jubla Triengen bietet ein vielfältiges Programm für Kinder und Jugendliche. Von wöchentlichen Gruppenstunden bis zu unvergesslichen Lagern ist für jeden etwas dabei. Tauche ein in unsere Welt und entdecke, was die Jubla so einzigartig macht."}$seed$::jsonb, $seed${}$seed$::jsonb, 7, true),
  ($seed$offering_detail$seed$, $seed$/angebote/:id$seed$, $seed$offering_detail$seed$, NULL, NULL, $seed${"notFoundTitle":"Angebot nicht gefunden","backLabel":"Zurück zur Übersicht"}$seed$::jsonb, 8, true),
  ($seed$posts$seed$, $seed$/posts$seed$, $seed$posts$seed$, $seed${"image":"https://images.unsplash.com/photo-1502086223501-681a6a508d52?auto=format&fit=crop&q=80","title":"Aktuelles"}$seed$::jsonb, $seed${"title":"Neuigkeiten aus der Schar","description":"Hier findest du Berichte über vergangene Anlässe, wichtige Informationen und Neuigkeiten."}$seed$::jsonb, $seed${}$seed$::jsonb, 9, true),
  ($seed$post_detail$seed$, $seed$/posts/:id$seed$, $seed$post_detail$seed$, NULL, NULL, $seed${"notFoundTitle":"Beitrag nicht gefunden","backLabel":"Zurück zur Übersicht","downloadsTitle":"Downloads & Infos","downloadLabel":"Download"}$seed$::jsonb, 10, true),
  ($seed$gallery$seed$, $seed$/galerie$seed$, $seed$gallery$seed$, $seed${"title":"Foto Gallerie","subtitle":"Erleben Sie die Abenteuer unserer Jugendgruppe durch unsere Fotogalerie","image":"https://picsum.photos/seed/hero/1200/400?grayscale"}$seed$::jsonb, NULL, $seed${}$seed$::jsonb, 11, false),
  ($seed$album_detail$seed$, $seed$/galerie/:id$seed$, $seed$album_detail$seed$, $seed${"title":"Album","subtitle":"Explore our photo album","image":"https://picsum.photos/seed/hero/1200/400?grayscale"}$seed$::jsonb, NULL, $seed${"notFoundTitle":"Album not found","backLabel":"Back to Gallery"}$seed$::jsonb, 12, false),
  ($seed$contact$seed$, $seed$/kontakt$seed$, $seed$contact$seed$, $seed${"title":"Kontakt & Mitmachen","subtitle":"Wir freuen uns von dir zu hören!","image":"https://images.unsplash.com/photo-1529156069898-49953e39b3ac?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"}$seed$::jsonb, NULL, $seed${}$seed$::jsonb, 13, true),
  ($seed$impressum$seed$, $seed$/impressum$seed$, $seed$legal$seed$, $seed${"title":"Impressum","subtitle":"Rechtliche Informationen","image":"https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"}$seed$::jsonb, NULL, $seed${}$seed$::jsonb, 14, true),
  ($seed$data_protection$seed$, $seed$/datenschutz$seed$, $seed$legal$seed$, $seed${"title":"Datenschutzerklärung","subtitle":"Wir respektieren deine Privatsphäre","image":"https://images.unsplash.com/photo-1516321497487-e288fb19713f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80"}$seed$::jsonb, NULL, $seed${"lastUpdated":"26. Februar 2024"}$seed$::jsonb, 15, true),
  ($seed$not_found$seed$, $seed$*$seed$, $seed$not_found$seed$, NULL, NULL, $seed${"code":"404","title":"Uups! Diese Seite haben wir wohl im Wald verloren.","description":"Vielleicht hast du dich verlaufen? Keine Sorge, im Lager finden wir immer einen Weg zurück.","buttonText":"Zurück zur Startseite","backgroundImage":"https://image.jimcdn.com/cdn-cgi/image//app/cms/storage/image/path/sb21156d07b64a771/backgroundarea/ib36b1240ebbc0855/version/1556893189/image.jpg"}$seed$::jsonb, 100, true);

INSERT INTO sections (page_key, component, props, sort_order) VALUES
  ($seed$home$seed$, $seed$hero$seed$, $seed${"backgroundImage":"https://media.jubla-triengen.ch/main.jpg","lines":["Abenteuer.","Freundschaft.","Lagerleben."],"subtitle":"Erlebe unvergessliche Momente in der Natur mit der Jubla Triengen.","button":{"text":"Mehr erfahren","scrollTo":"about"}}$seed$::jsonb, 1),
  ($seed$home$seed$, $seed$feature_grid$seed$, $seed${"items":[{"icon":"tent","title":"Gruppenstunden","subtitle":"Spiel & Spass","description":"Regelmässige Treffen voller Spiele, Kreativität und Gemeinschaft."},{"icon":"mountain","title":"Ferienlager","subtitle":"Lagerabenteuer","description":"Unvergessliche Wochen in der Natur mit Lagerfeuer und Abenteuer."},{"icon":"tree-pine","title":"Events & Anlässe","subtitle":"Gemeinsam erleben","description":"Besondere Aktivitäten und Feste durchs ganze Jahr."}]}$seed$::jsonb, 2),
  ($seed$home$seed$, $seed$content_image_section$seed$, $seed${"id":"about","title":"Willkommen bei der Jubla Triengen","paragraphs":["Die Jubla Triengen ist mehr als nur eine Jugendorganisation. Wir sind eine Gemeinschaft von Abenteurern, die gemeinsam die Natur entdecken, Freundschaften fürs Leben schliessen und unvergessliche Erinnerungen schaffen.","Bei uns stehen Spass, Kreativität und das gemeinsame Erleben im Mittelpunkt. Ob bei wöchentlichen Gruppenstunden, aufregenden Ferienlagern oder besonderen Events - bei der Jubla ist für jedes Kind etwas dabei."],"image":{"src":"https://media.jubla-triengen.ch/placeholder-image.png","alt":"Kinder beim Wandern"},"button":{"text":"Unsere Angebote","link":"/angebote"},"decorativeCircle":true}$seed$::jsonb, 3),
  ($seed$home$seed$, $seed$card_section$seed$, $seed${"id":"highlights","title":"Unsere nächsten Highlights","orientation":"horizontal","backgroundColor":"white","button":{"text":"Zum Programm","link":"/anlässe"},"cardType":"event","dataSource":{"collection":"activities","limit":3}}$seed$::jsonb, 4),
  ($seed$home$seed$, $seed$card_section$seed$, $seed${"id":"news","title":"Neues aus der Jubla","orientation":"vertical","backgroundColor":"gradient","button":{"text":"Zu den Neuigkeiten","link":"/posts"},"cardType":"news","dataSource":{"collection":"posts","limit":2},"childrenWrapperClassName":"lg:col-span-full space-y-6"}$seed$::jsonb, 5),
  ($seed$about$seed$, $seed$content_image_section$seed$, $seed${"id":"what-is-jubla","title":"Was ist Jubla?","paragraphs":["Jungwacht Blauring (kurz Jubla) ist der grösste katholische Kinder- und Jugendverband der Schweiz. Ein Verband mit über 30’000 Mitgliedern, der für Offenheit, Freiraum und Gemeinschaft steht.","In der Jubla verbringen Kinder und Jugendliche vielfältige und altersgerechte Freizeit – unabhängig von Kirchenzugehörigkeit, Herkunft oder politischer Gesinnung.","Das Angebot in den lokalen Scharen (Ortsgruppen) reicht von regelmässigen Gruppenstunden über Scharanlässe bis hin zu Zelt- und Hauslagern."],"image":{"src":"https://media.jubla-triengen.ch/placeholder-image.png","alt":"Jubla Gruppe beim Spielen"},"button":{"text":"Lerne unser Leitungsteam kennen","link":"/leiter"},"imagePosition":"right"}$seed$::jsonb, 1),
  ($seed$about$seed$, $seed$content_image_section$seed$, $seed${"id":"values","title":"Unsere Grundsätze","paragraphs":["Die Jubla basiert auf fünf Grundsätzen: Zusammen sein, Mitbestimmen, Glauben leben, Kreativ sein und Natur erleben.","Diese Werte prägen unser Zusammenleben und unsere Aktivitäten. Wir bieten einen Freiraum, in dem sich Kinder und Jugendliche entfalten und ihre eigenen Fähigkeiten entdecken können.","Dabei steht das gemeinsame Erleben im Vordergrund. Wir pflegen einen respektvollen Umgang miteinander und übernehmen Verantwortung für uns und andere."],"image":{"src":"https://media.jubla-triengen.ch/placeholder-image.png","alt":"Lagerfeuer Stimmung"},"imagePosition":"left","backgroundColor":"bg-orange-50"}$seed$::jsonb, 2),
  ($seed$about$seed$, $seed$content_image_section$seed$, $seed${"id":"history","title":"Jubla Triengen","paragraphs":["Die Jubla Triengen ist seit vielen Jahren ein fester Bestandteil des Dorflebens. Mit unseren engagierten Leiterinnen und Leitern bieten wir den Kindern und Jugendlichen aus Triengen und Umgebung ein abwechslungsreiches Freizeitprogramm.","Unser Highlight ist das jährliche Sommerlager, in dem wir zwei Wochen lang gemeinsam Abenteuer erleben, am Lagerfeuer singen und in Zelten übernachten.","Komm vorbei und schnuppere Jubla-Luft! Wir freuen uns auf dich."],"image":{"src":"https://media.jubla-triengen.ch/placeholder-image.png","alt":"Gruppenfoto Jubla Triengen"},"imagePosition":"right"}$seed$::jsonb, 3),
  ($seed$contact$seed$, $seed$content_image_section$seed$, $seed${"id":"contact","title":"Kontaktiere uns","paragraphs":["Hast du Fragen zur Jubla, zu unseren Anlässen oder möchtest du einfach mal reinschnuppern? Zögere nicht, uns zu kontaktieren.","Du erreichst uns am besten per E-Mail oder über unsere Scharleitung."],"image":{"src":"https://images.unsplash.com/photo-1577563908411-5077b6dc7624?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80","alt":"Kontakt aufnehmen"},"imagePosition":"right","contactDetails":{"email":"info@jublatriengen.ch","address":["Jubla Triengen","Kirchgasse 4","6234 Triengen"]}}$seed$::jsonb, 1);

INSERT INTO activities (id, title, event_date, short_description, long_description, image, sort_order, published) VALUES
  ($seed$sommerlager-2024$seed$, $seed$Sommerlager 2024$seed$, $seed$08.07.2024 - 20.07.2024$seed$, $seed$Unser jährliches Highlight: Das Sommerlager! Zwei Wochen voller Abenteuer, Spass und Gemeinschaft.$seed$, $seed$
      Das Sommerlager ist das absolute Highlight in unserem Jubla-Jahr. Wir verbringen zwei Wochen gemeinsam in einem Lagerhaus oder im Zelt. 
      Jeden Tag erleben wir spannende Abenteuer, spielen Geländespiele, singen am Lagerfeuer und geniessen die Zeit zusammen.
      
      Dieses Jahr geht es ins wunderschöne Graubünden. Das Leitungsteam hat ein abwechslungsreiches Programm zusammengestellt, das keine Wünsche offen lässt.
      Egal ob Gross oder Klein, im Sommerlager ist für jeden etwas dabei.
      
      Packt eure Rucksäcke und kommt mit uns auf eine unvergessliche Reise!
    $seed$, $seed$https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&q=80$seed$, $seed$1$seed$, $seed$true$seed$),
  ($seed$papiersammlung-fruehling$seed$, $seed$Papiersammlung Frühling$seed$, $seed$16.03.2024$seed$, $seed$Gemeinsam sammeln wir Altpapier in Triengen und bessern unsere Lagerkasse auf.$seed$, $seed$
      Es ist wieder soweit: Die Papiersammlung steht an! Wir treffen uns am Samstagmorgen, um gemeinsam das Altpapier in der Gemeinde einzusammeln.
      Dies ist eine wichtige Einnahmequelle für unsere Schar und hilft uns, die Lagerbeiträge tief zu halten.
      
      Wir sind auf die Hilfe aller Kinder und Leiter angewiesen. Für Verpflegung ist natürlich gesorgt.
      Nach getaner Arbeit gibt es ein feines Zmittag für alle Helferinnen und Helfer.
    $seed$, $seed$https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80$seed$, $seed$2$seed$, $seed$true$seed$),
  ($seed$gruppenstunde-alle$seed$, $seed$Scharanlass: Schnitzeljagd$seed$, $seed$04.05.2024$seed$, $seed$Ein spannender Nachmittag für die ganze Schar mit einer grossen Schnitzeljagd durch den Wald.$seed$, $seed$
      Wir laden alle Kinder und Jugendlichen zu einem grossen Scharanlass ein. Wir werden gemeinsam eine riesige Schnitzeljagd veranstalten.
      Wer kann die Hinweise am schnellsten entschlüsseln und den Schatz finden?
      
      Zieht euch wettergerecht an und nehmt gute Laune mit. Wir freuen uns auf euch!
    $seed$, $seed$https://images.unsplash.com/photo-1533240332313-0db49b459ad6?auto=format&fit=crop&q=80$seed$, $seed$3$seed$, $seed$true$seed$);

INSERT INTO posts (id, title, post_date, short_description, long_description, image, sort_order, published) VALUES
  ($seed$jubla-tag-2024$seed$, $seed$Rückblick Jubla Tag 2024$seed$, $seed$10.09.2024$seed$, $seed$Ein toller Tag voller Spiel und Spass liegt hinter uns. Hier ist der Bericht.$seed$, $seed$
      Am vergangenen Samstag fand der nationale Jubla-Tag statt. Auch wir von der Jubla Triengen waren natürlich mit dabei!
      Unter dem Motto "Lebensfreude" haben wir einen abwechslungsreichen Nachmittag für alle Kinder und Jugendlichen aus der Region organisiert.

      Wir starteten mit einem grossen Geländespiel im Wald, bei dem Geschicklichkeit und Teamgeist gefragt waren.
      Anschliessend gab es ein feines Zvieri und Zeit zum gemütlichen Beisammensein.

      Wir danken allen, die dabei waren und freuen uns schon auf das nächste Jahr!
    $seed$, $seed$https://images.unsplash.com/photo-1526662092594-e98c1e35652b?auto=format&fit=crop&q=80$seed$, $seed$1$seed$, $seed$true$seed$);

INSERT INTO attachments (collection, entity_id, name, url, sort_order) VALUES
  ($seed$activities$seed$, $seed$sommerlager-2024$seed$, $seed$Infoheft Sommerlager$seed$, $seed$#$seed$, $seed$1$seed$),
  ($seed$activities$seed$, $seed$sommerlager-2024$seed$, $seed$Packliste$seed$, $seed$#$seed$, $seed$2$seed$),
  ($seed$activities$seed$, $seed$sommerlager-2024$seed$, $seed$Anmeldeformular$seed$, $seed$#$seed$, $seed$3$seed$),
  ($seed$activities$seed$, $seed$papiersammlung-fruehling$seed$, $seed$Einsatzplan$seed$, $seed$#$seed$, $seed$1$seed$);

INSERT INTO attachments (collection, entity_id, name, url, sort_order) VALUES
  ($seed$posts$seed$, $seed$jubla-tag-2024$seed$, $seed$Flyer$seed$, $seed$#$seed$, $seed$1$seed$),
  ($seed$posts$seed$, $seed$jubla-tag-2024$seed$, $seed$Fotos$seed$, $seed$https://pixabay.com/get/g0c18448bcc7948c6657846233acffb181282e7dde42a0b674dc7a4464c3eb334321b9c3ee25043a496b4bfa856981b9e2b38afb3a12bf146f913f3cc981c37760f0f148cf1d81ae3a5fab8c42bddaa6b_1920.jpg?attachment=$seed$, $seed$2$seed$);

INSERT INTO offerings (id, title, short_description, long_description, image, sort_order, published) VALUES
  ($seed$gruppenstunden$seed$, $seed$Gruppenstunden$seed$, $seed$Wöchentliche Treffen in altersspezifischen Gruppen voller Spiel und Spass.$seed$, $seed$
      Die Gruppenstunde ist das Herzstück der Jubla. Kinder und Jugendliche gleichen Alters treffen sich regelmässig, meist einmal pro Woche oder alle zwei Wochen, in ihrer Gruppe.
      
      Die Gruppen werden von einem Leitungsteam betreut, das abwechslungsreiche Programme zusammenstellt. Ob Basteln, Spielen im Wald, Kochen oder gemeinsame Ausflüge – in der Gruppenstunde ist immer etwas los.
      
      Hier entstehen Freundschaften fürs Leben. Man lernt, aufeinander Rücksicht zu nehmen, gemeinsam Ziele zu erreichen und Verantwortung zu übernehmen. Aber vor allem steht der Spass im Vordergrund!
      
      Interessiert an einer Schnuppergruppenstunde? Melde dich bei uns!
    $seed$, $seed$https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&q=80$seed$, $seed$1$seed$, $seed$true$seed$),
  ($seed$lager$seed$, $seed$Lager$seed$, $seed$Unvergessliche Erlebnisse in unseren Zelt- und Hauslagern.$seed$, $seed$
      Unsere Lager sind die Highlights des Jahres! Wir führen in der Regel ein Sommerlager und oft auch ein Pfingst- oder Winterlager durch.
      
      Im Sommerlager verbringen wir eine bis zwei Wochen gemeinsam, oft im Zelt oder in einem Lagerhaus. Wir tauchen ein in eine andere Welt, passend zu einem Lagermotto.
      
      Das Lagerleben bietet unzählige Möglichkeiten: Geländespiele, Lagerfeuer, Wanderungen, Pioniertechnik, Singen, Basteln und vieles mehr.
      
      Es ist eine Zeit ohne Eltern, in der man selbstständiger wird und die Gemeinschaft intensiv erlebt. Das Lageressen aus der grossen Küche und die Nächte im Schlafsack gehören einfach dazu.
    $seed$, $seed$https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&q=80$seed$, $seed$2$seed$, $seed$true$seed$),
  ($seed$scharanlaesse$seed$, $seed$Scharanlässe$seed$, $seed$Gemeinsame Aktivitäten mit der ganzen Schar - Gross und Klein zusammen.$seed$, $seed$
      Neben den Gruppenstunden und Lagern gibt es die Scharanlässe. Hier trifft sich die ganze Jubla-Schar, von den jüngsten Wölfen bis zu den ältesten Leitern.
      
      Typische Scharanlässe sind der Scharstart, Weihnachten im Wald, der 1. August-Brunch oder ein gemeinsamer Ausflugstag.
      
      Diese Anlässe stärken das Zusammengehörigkeitsgefühl über die Altersgruppen hinweg. Die Kleinen schauen zu den Grossen auf, und die Grossen übernehmen Verantwortung für die Kleinen.
      
      Es sind oft Anlässe, zu denen auch Eltern und Freunde eingeladen sind, um einen Einblick in unser Jubla-Leben zu bekommen.
    $seed$, $seed$https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&q=80$seed$, $seed$3$seed$, $seed$true$seed$),
  ($seed$aufnahme$seed$, $seed$Aufnahme$seed$, $seed$Der feierliche Moment, wenn du offiziell Teil unserer Jubla-Familie wirst.$seed$, $seed$
      Die Aufnahme ist ein spezieller Anlass, bei dem neue Mitglieder feierlich in die Schar aufgenommen werden.
      
      Meist findet dies in einem Gottesdienst oder einer speziellen Zeremonie statt. Die Neumitglieder erhalten oft ein Jubla-Hemd oder ein Halstuch als Zeichen ihrer Zugehörigkeit.
      
      Es ist ein stolzer Moment für jedes Kind, wenn es "richtig" dazugehört. Auch für die Eltern ist es ein schöner Anlass, den Start ihres Kindes in der Jubla zu feiern.
      
      Nach der Aufnahme bist du offiziell ein Jublaner oder eine Jublanerin und trägst den "Jubla-Spirit" mit dir!
    $seed$, $seed$https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80$seed$, $seed$4$seed$, $seed$true$seed$);

INSERT INTO leaders (id, name, nickname, role, image, background_image, description, long_description, email, phone, birthday, courses, jubla_roles, profession, hobbies, jubla_highlight, sort_order, published) VALUES
  ($seed$meo-arnold$seed$, $seed$Meo Arnold$seed$, $seed$-$seed$, $seed$Gruppenleiter 1./2. Sek Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/meo-arnold$seed$, $seed$https://media.jubla-triengen.ch/leaders/meo-arnold-background$seed$, $seed$In meiner Freizeit spiele ich Fussball beim Team Surental. Zudem mache ich gerne was mit meinen Freunden.$seed$, $seed$In meiner Freizeit spiele ich Fussball beim Team Surental. Zudem mache ich gerne was mit meinen Freunden.$seed$, $seed$meoarnold06@gmail.com$seed$, NULL, $seed$Oktober 2006$seed$, $seed$GLK, SLRG$seed$, $seed$Ressort Lager$seed$, $seed$Elektroinstallateur EFZ$seed$, $seed$Fussball, Freunde treffen$seed$, $seed$Für mich ist jeder JuBla-Anlass wieder ein neues Highlight. Ich freue mich immer, zusammen mit meinen JuBla-Kindern und den Mitleitern eine tolle und coole Zeit zu verbringen - sei es im Lager, in einer Gruppenstunde oder an einem Scharanlass.$seed$, $seed$1$seed$, $seed$true$seed$),
  ($seed$riana-arnold$seed$, $seed$Riana Arnold$seed$, $seed$Ri$seed$, $seed$Gruppenleiterin 1./2. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/riana-arnold$seed$, $seed$https://media.jubla-triengen.ch/leaders/riana-arnold-background$seed$, $seed$Wenn ich nicht gerade in der JuBla anzutreffen bin, zeichne und bastle ich gerne in meiner Freizeit.$seed$, $seed$Wenn ich nicht gerade in der JuBla anzutreffen bin, zeichne und bastle ich gerne in meiner Freizeit. In den Ferien liebe ich es ans Meer zu reisen und den ganzen Tag zu baden.  $seed$, $seed$riana.arnold@bluewin.ch$seed$, NULL, $seed$Januar 2007$seed$, $seed$GLK$seed$, $seed$Ressort Kreativ$seed$, $seed$Kauffrau EFZ bei der Trisa AG$seed$, $seed$Zeichnen, Basteln, Reisen$seed$, $seed$Mein JuBla Highlight ist das alljährliche JuBla-Lager, welches ich seit der 3. Klasse besuche. Man erlebt viele coole, unvergessliche Momente mit Freunden, kann sich bei Games auspowern und verbringt zwei tolle Wochen in der Natur und am Lagerfeuer.$seed$, $seed$2$seed$, $seed$true$seed$),
  ($seed$melvin-blum$seed$, $seed$Melvin Blum$seed$, $seed$Mele$seed$, $seed$Gruppenleiter 15er Team$seed$, $seed$https://media.jubla-triengen.ch/leaders/melvin-blum$seed$, $seed$https://media.jubla-triengen.ch/leaders/melvin-blum-background$seed$, $seed$In meiner Freizeit gehe ich Pistolenschiessen und mache mit Kollegen ab.$seed$, $seed$In meiner Freizeit gehe ich Pistolenschiessen und mache mit Kollegen ab.$seed$, $seed$melvin.jurt@gmx.ch$seed$, NULL, $seed$August 2005$seed$, $seed$GLK$seed$, $seed$Ressort Kreativ$seed$, $seed$Lernender Fachmann Betriebsunterhalt$seed$, $seed$Pistolenschiessen, Mit Kollegen abmachen$seed$, $seed$JuBla Lager: Weil man zwei Wochen lang mit anderen Personen aus der JuBla coole Momente erlebt.$seed$, $seed$3$seed$, $seed$true$seed$),
  ($seed$noah-blum$seed$, $seed$Noah Blum$seed$, $seed$Bär$seed$, $seed$Gruppenleiter 3./4. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/noah-blum$seed$, $seed$https://media.jubla-triengen.ch/leaders/noah-blum-background$seed$, $seed$Ich bin viel mit Freunden unterwegs, fahre Motorrad und gehe ab und zu gerne schwimmen.$seed$, $seed$Ich bin viel mit Freunden unterwegs, fahre Motorrad und gehe ab und zu gerne schwimmen.$seed$, $seed$noahelias.blum@gmail.com$seed$, NULL, $seed$September 2002$seed$, $seed$GLK$seed$, $seed$Ressort Lager$seed$, $seed$Automobilmechatroniker Fachrichtung Nutzfahrzeuge bei Galliker Transport und Logistik AG$seed$, $seed$Mit Freunden unterwegs sein, Motorrad fahren, Schwimmen$seed$, $seed$Mein Highlight ist das Lager, da es zwei Wochen fernab von allem ist und man komplett weg vom Alltag kommt und mit der Schar etwas unternehmen kann.$seed$, $seed$4$seed$, $seed$true$seed$),
  ($seed$patrick-blum$seed$, $seed$Patrick Blum$seed$, $seed$Pädi$seed$, $seed$Gruppenleiter 3./4. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/patrick-blum$seed$, $seed$https://media.jubla-triengen.ch/leaders/patrick-blum-background$seed$, $seed$In meiner Freizeit treibe ich viel Sport und bin im Turnverein Winikon.$seed$, $seed$In meiner Freizeit treibe ich viel Sport und bin im Turnverein Winikon. Dazu kommt die JuBla, in der ich seit klein auf bin und immer noch sehr Spass daran finde. Ansonsten bin ich begeistert am Skateboard fahren.$seed$, $seed$Patrick@blum.tv$seed$, NULL, $seed$April 2005$seed$, $seed$GLK, SLK$seed$, $seed$Ressort Lager, Lagerleitung$seed$, $seed$Automatiker EFZ bei Kipfer & Burdak GmbH$seed$, $seed$Sport, Turnverein Winikon, JuBla, Skateboard fahren$seed$, $seed$Zu meinen grössten Highlights der JuBla gehört das Lager. Ich durfte seit der dritten Klasse in jedes Lager und es waren immer die besten zwei Wochen vom Jahr. Man versteht sich mit gross und klein, findet neue Freunde und macht super tolle Spiele, die auch sehr herausfordernd sind für Kopf und Körper.$seed$, $seed$5$seed$, $seed$true$seed$),
  ($seed$raphael-buechler$seed$, $seed$Raphael Büchler$seed$, $seed$Büchi$seed$, $seed$Gruppenleiter 5./6. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/raphael-buechler$seed$, $seed$https://media.jubla-triengen.ch/leaders/raphael-buechler-background$seed$, $seed$Ich bin im Jungschützenverein, habe Schlagzeug gespielt und bin viel mit Kollegen unterwegs.$seed$, $seed$Ich bin im Jungschützenverein, habe Schlagzeug gespielt und bin viel mit Kollegen unterwegs.$seed$, $seed$raphael_buechler@outlook.com$seed$, NULL, $seed$November 2007$seed$, $seed$GLK$seed$, $seed$Ressort Bau & Material$seed$, $seed$Lernender Elektroinstallateur EFZ bei Frey electric$seed$, $seed$Jungschützenverein, Schlagzeug, Mit Kollegen unterwegs sein$seed$, $seed$Als Kind fand ich das JuBla-Lager immer toll. Zum Beispiel das Drogengame war immer ein Highlight des Lagers. Es war immer grossartig, die Spannung zu erleben und den Zusammenhalt der Gruppe zu sehen.$seed$, $seed$6$seed$, $seed$true$seed$),
  ($seed$ivan-fischer$seed$, $seed$Ivan Fischer$seed$, $seed$-$seed$, $seed$Gruppenleiter 1./2. Sek Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/ivan-fischer$seed$, $seed$https://media.jubla-triengen.ch/leaders/ivan-fischer-background$seed$, $seed$Neben der JuBla spiele ich Tischtennis im TTC Schenkon und nehme auch an Turnieren teil.$seed$, $seed$Neben der JuBla spiele ich noch Tischtennis im TTC Schenkon, bei welchem ich auch an Turnieren teilnehme. In meiner Freizeit verbringe ich auch gerne Zeit mit Freunden.$seed$, $seed$ivan_f@bluewin.ch$seed$, NULL, $seed$September 2006$seed$, $seed$GLK$seed$, $seed$Ressort Bau & Material$seed$, $seed$Lernender Polymechaniker EFZ bei der Trisa AG$seed$, $seed$Tischtennis, Turniere, Zeit mit Freunden$seed$, $seed$Ich habe es schon seit der 3. Klasse gemocht in die Gruppenstunden zu gehen. Deshalb freut es mich umso mehr, diese jetzt auch zu leiten. Ich mag es auch sehr an Anlässen gegen andere Scharen teilzunehmen.$seed$, $seed$7$seed$, $seed$true$seed$),
  ($seed$lars-fischer$seed$, $seed$Lars Fischer$seed$, $seed$Leslyy$seed$, $seed$Gruppenleiter 15er Team$seed$, $seed$https://media.jubla-triengen.ch/leaders/lars-fischer$seed$, $seed$https://media.jubla-triengen.ch/leaders/lars-fischer-background$seed$, $seed$In meiner Freizeit bin ich gerne draussen, verbringe gemütliche Abende mit Freunden und mag Musik.$seed$, $seed$In meiner Freizeit bin ich gerne draussen und mag es, mit meinen Freunden einen gemütlichen Abend zu verbringen. Ich mag Musik und stehe teilweise selbst hinter dem DJ-Pult.$seed$, $seed$hello@fischer-lars.ch$seed$, NULL, $seed$November 2004$seed$, $seed$GLK$seed$, $seed$Hauptleiter JuBla Region Sursee, Teamleiter Informatik & Kommunikation$seed$, $seed$Softwareentwickler bei auviso ag$seed$, $seed$Draussen sein, Zeit mit Freunden, Musik, DJ$seed$, $seed$Seit ich sieben bin, gehe ich in die JuBla. Es gab wahnsinnig viele Highlights. Die unterhaltsamen und lustigen Abenden mit den JuBla-Freunden ob im Lager oder am Wochenende schätze ich am meisten. Ich mag es, anderen Menschen in den Gruppenstunden eine Freude zu bereiten. Fun Fact: Seit der ersten GruStu war ich immer der grösste der Stufe.$seed$, $seed$8$seed$, $seed$true$seed$),
  ($seed$noel-haefliger$seed$, $seed$Noel Häfliger$seed$, $seed$Nöli/Nög$seed$, $seed$Gruppenleiter 15er Team$seed$, $seed$https://media.jubla-triengen.ch/leaders/noel-haefliger$seed$, $seed$https://media.jubla-triengen.ch/leaders/noel-haefliger-background$seed$, $seed$Neben der JuBla mache ich gerne etwas mit meinen Freunden, spiele Fussball oder gehe im Wald bräteln.$seed$, $seed$Neben der JuBla mache ich gerne etwas mit meinen Freunden, wie zum Beispiel Fussball spielen oder in den Wald bräteln gehen. Zudem erfreue ich mich an Serien und Filmen.$seed$, $seed$noelhafliger@gmail.com$seed$, NULL, $seed$Februar 2004$seed$, $seed$GLK$seed$, $seed$Ressort Kreativ$seed$, $seed$Gymnasiast an der Kantonsschule Sursee$seed$, $seed$Zeit mit Freunden, Fussball, Bräteln, Serien und Filme$seed$, $seed$Das Highlight für mich in der JuBla ist das Lager, denn dort kann man zwei Wochen Spiele, so wie auch Abenteuer geniessen. Der Gruppenzusammenhalt ist im SOLA immer besonders aktiv und stark.$seed$, $seed$9$seed$, $seed$true$seed$),
  ($seed$mathias-heim$seed$, $seed$Mathias Heim$seed$, $seed$Mätu$seed$, $seed$Gruppenleiter 15er Team$seed$, $seed$https://media.jubla-triengen.ch/leaders/mathias-heim$seed$, $seed$https://media.jubla-triengen.ch/leaders/mathias-heim-background$seed$, $seed$In meiner Freizeit bin ich gerne mit Freunden zusammen, zelte im Wald und bin oft im Skatepark.$seed$, $seed$In meiner Freizeit bin ich gerne mit Freunden zusammen. Wir zelten im Wald oder arbeiten an einem Projekt. Öfters bin ich auch im Skatepark anzutreffen.$seed$, $seed$heim.mathias@hotmail.com$seed$, NULL, $seed$Januar 2005$seed$, $seed$GLK$seed$, $seed$Ressort Bau & Material$seed$, $seed$Möbelschreiner EFZ bei Urs Dubach AG$seed$, $seed$Zeit mit Freunden, Zelten im Wald, Projekte, Skatepark$seed$, $seed$Mein JuBla Highlight war das Sommerlager 2020 in der 3ten Oberstufe. Die Lagerstory war super spannend. Das Leiterteam hat die zwei Wochen perfekt gestaltet.$seed$, $seed$10$seed$, $seed$true$seed$),
  ($seed$gabriel-illi$seed$, $seed$Gabriel Illi$seed$, $seed$Gäbu$seed$, $seed$Gruppenleiter 1./2. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/gabriel-illi$seed$, $seed$https://media.jubla-triengen.ch/leaders/gabriel-illi-background$seed$, $seed$In meiner Freizeit spiele ich Volleyball im VBC Triengen.$seed$, $seed$In meiner Freizeit spiele ich Volleyball im VBC Triengen.$seed$, $seed$gabriel.illi@gmx.de$seed$, NULL, $seed$Dezember 2008$seed$, $seed$-$seed$, $seed$Ressort Bau & Material$seed$, $seed$Lernender Schreiner beim Albisser Geuensee$seed$, $seed$Volleyball$seed$, $seed$Das Highlight von der JuBla sind jedes Jahr die Sommerlager.$seed$, $seed$11$seed$, $seed$true$seed$),
  ($seed$sarina-illi$seed$, $seed$Sarina Illi$seed$, $seed$Sare$seed$, $seed$Gruppenleiterin 1./2. Sek Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/sarina-illi$seed$, $seed$https://media.jubla-triengen.ch/leaders/sarina-illi-background$seed$, $seed$In meiner Freizeit spiele ich seit vielen Jahren Volleyball im VBC Triengen und treffe mich gerne mit Freunden.$seed$, $seed$In meiner Freizeit spiele ich schon seit vielen Jahren Volleyball im VBC Triengen. Ich verbringe meine Zeit auch sehr gerne mit der JuBla und treffe mich mit Freunden.$seed$, $seed$sarina.illi@gmx.de$seed$, NULL, $seed$Januar 2006$seed$, $seed$GLK$seed$, $seed$Ressort Kreativ$seed$, $seed$Gestalterin Werbetechnik bei Pinato Graphics AG$seed$, $seed$Volleyball, JuBla, Freunde treffen$seed$, $seed$Das JuBla Lager ist immer wieder das Highlight des Jahres. Man erlebt zwei abenteuerliche und erlebnisreiche Wochen in der man die Leute viel besser kennen lernt und immer Spass hat.$seed$, $seed$12$seed$, $seed$true$seed$),
  ($seed$anja-kaufmann$seed$, $seed$Anja Kaufmann$seed$, $seed$-$seed$, $seed$Gruppenleiterin 1./2. Sek Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/anja-kaufmann$seed$, $seed$https://media.jubla-triengen.ch/leaders/anja-kaufmann-background$seed$, $seed$Neben der JuBla betätige ich mich gerne sportlich und unternehme viel mit Freunden.$seed$, $seed$Neben der JuBla betätige ich mich gerne sportlich. In meinen Ferien gehe ich gerne ins Ausland mit meiner Familie oder mit meinen Freunden. Ich unternehme gerne etwas mit meinen Freunden und mache mit ihnen einen tollen Abend.$seed$, $seed$kaufmann.anja06@gmail.com$seed$, NULL, $seed$Oktober 2006$seed$, $seed$GLK, SLK$seed$, $seed$Ressort Finanzen, Lagerleitung$seed$, $seed$Kauffrau EFZ bei der F. Fischer AG$seed$, $seed$Sport, Reisen, Zeit mit Freunden$seed$, $seed$Das Sommerlager, die Gruppenstunden, die Scharanlässe. Ich finde alle diese Sachen gehören zu meinem JuBla Highlight. Ich bin schon seit ich 10 Jahre alt bin in der JuBla und es gibt überall etwas zum Lachen. Ich freue mich jedes Mal wenn es wieder einen Anlass mit der JuBla gibt und jeder eine tolle und unvergessliche Zeit erleben kann.$seed$, $seed$13$seed$, $seed$true$seed$),
  ($seed$karol-kaufmann$seed$, $seed$Karol Kaufmann$seed$, $seed$Kari$seed$, $seed$Gruppenleiter 1./2. Sek Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/karol-kaufmann$seed$, $seed$https://media.jubla-triengen.ch/leaders/karol-kaufmann-background$seed$, $seed$Ich spiele gerne Klarinette, bin in der Jugendmusik Surental und bin gerne in der JuBla tätig.$seed$, $seed$Ich spiele gerne Klarinette und bin in der Jugendmusik Surental. Natürlich bin ich auch gerne in der JuBla tätig.$seed$, $seed$kaufmannkarol2@gmail.com$seed$, NULL, $seed$Mai 2005$seed$, $seed$GLK$seed$, $seed$Regionalleitung (Region Sursee), Ressort Kommunikation & Informatik$seed$, $seed$Milchtechnologe EFZ bei Emmi Kaltbach$seed$, $seed$Klarinette, Jugendmusik Surental, JuBla$seed$, $seed$Mein JuBla Highlight ist das erste Hauslager als Leiter. Es war eine sehr lustige Zeit. Vor allem das Planen der Spiele und Ausführen war cool!$seed$, $seed$14$seed$, $seed$true$seed$),
  ($seed$magdalena-kaufmann$seed$, $seed$Magdalena Kaufmann$seed$, $seed$Magda$seed$, $seed$Gruppenleiterin 5./6. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/magdalena-kaufmann$seed$, $seed$https://media.jubla-triengen.ch/leaders/magdalena-kaufmann-background$seed$, $seed$In meiner Freizeit bin ich sportlich und musikalisch unterwegs und mache gerne etwas mit meinen Freunden.$seed$, $seed$In meiner Freizeit bin ich sportlich und musikalisch unterwegs. Ich spiele Volleyball im VBC Triengen und Oboe in der Jugendmusik Surental / Michelsamt. Ich mache aber auch sehr gerne etwas mit meinen Freunden.$seed$, $seed$kaufmannmagdalena14@gmail.com$seed$, NULL, $seed$Juni 2010$seed$, $seed$-$seed$, $seed$Ressort Kreativ$seed$, $seed$Lernende MPA im PFGM Wauwil$seed$, $seed$Volleyball, Oboe, Jugendmusik, Zeit mit Freunden$seed$, $seed$Mein JuBla Highlight was und ist immer das Sommerlager. In der JuBla habe ich viele wichtige Freunde gefunden. Gemütlich am Lagerfeuer sitzen was schon immer mein Favorit. Aber auch das Raclette essen im 15er Lager war ein Highlight.$seed$, $seed$15$seed$, $seed$true$seed$),
  ($seed$natalia-kaufmann$seed$, $seed$Natalia Kaufmann$seed$, $seed$Nat$seed$, $seed$Gruppenleiterin 1./2. Sek Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/natalia-kaufmann$seed$, $seed$https://media.jubla-triengen.ch/leaders/natalia-kaufmann-background$seed$, $seed$Wenn ich mich nicht mit der JuBla beschäftige, leite ich Geräteturn-Kids in Winikon und trainiere selbst.$seed$, $seed$Wenn ich mich nicht gerade mit der JuBla beschäftige, könnt ihr mich in der Turnhalle in Winikon antreffen. Dort leite ich die Geräteturn-Kids und gehe auch selbst in die Trainings der Aktiven. Ansonsten verbringe ich meine Zeit sehr gerne mit meinen Freunden.$seed$, $seed$kaufmannnatalia6@gmail.com$seed$, NULL, $seed$Juni 2003$seed$, $seed$GLK$seed$, $seed$Teamleiterin Kreativ, Protokoll$seed$, $seed$Studentin Rechtswissenschaften an der Universität Bern, Eidgenössische Maturität$seed$, $seed$Geräteturnen, Leiten, Zeit mit Freunden$seed$, $seed$Für mich ist das Lager ganz klar das absolute Highlight, da man dort mit ganz vielen verschiedenen Leuten, ob Kindern, Leitern oder auch der Küche, ganz viel grossartige Momente erlebt und Erfahrungen sammelt. Über diese kann man sich dann noch über viele Jahre hinweg zusammen unterhalten und darüber lachen.$seed$, $seed$16$seed$, $seed$true$seed$),
  ($seed$nicole-kaufmann$seed$, $seed$Nicole Kaufmann$seed$, $seed$Nici$seed$, $seed$Gruppenleiterin 5./6. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/nicole-kaufmann$seed$, $seed$https://media.jubla-triengen.ch/leaders/nicole-kaufmann-background$seed$, $seed$Neben der JuBla bin ich im Turnverein Triengen und im Geräteturnen, im Winter gerne im Schnee.$seed$, $seed$Neben der JuBla bin ich im Turnverein Triengen wie auch im Geräteturnen. Im Winter liebe ich es im Schnee und auf der Piste zu sein. Wenn ich noch Zeit finde, mag ich es mich kreativ auszuleben oder mich in der Küche auszutoben.$seed$, $seed$nicole.k.13plus@gmail.com$seed$, NULL, $seed$Januar 2008$seed$, $seed$GLK$seed$, $seed$Ressort Lager$seed$, $seed$Lernende FaGe EFZ$seed$, $seed$Turnverein, Geräteturnen, Wintersport, Kreatives, Kochen$seed$, $seed$Meine JuBla Highlights sind die gemütlichen Stunden am Lagerfeuer. Ich liebe es seit der dritten Klasse wie eine Grossfamilie am Lagerfeuer ein Singsong zu haben und so den Abend gemütlich ausklingen zu lassen. Die Stunden sind jedes Jahr unvergesslich und ich freue mich nach dem Lager schon auf das nächste.$seed$, $seed$17$seed$, $seed$true$seed$),
  ($seed$stefanie-kaufmann$seed$, $seed$Stefanie Kaufmann$seed$, $seed$Steffi$seed$, $seed$Gruppenleiterin 5./6. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/stefanie-kaufmann$seed$, $seed$https://media.jubla-triengen.ch/leaders/stefanie-kaufmann-background$seed$, $seed$Neben der JuBla gehe ich gerne ins Geräteturnen im STV Winikon und verbringe schöne Abende mit Kollegen.$seed$, $seed$Neben der JuBla gehe ich gerne ins Geräteturnen im STV Winikon. Mit Kollegen verbringe ich auch gerne schöne Abende zusammen.$seed$, $seed$stefanie.kaufmann09@gmail.com$seed$, NULL, $seed$Februar 2009$seed$, $seed$-$seed$, $seed$Ressort Kreativ$seed$, $seed$Lernende FaGe EFZ im LUKS Spital Sursee$seed$, $seed$Geräteturnen, Zeit mit Kollegen$seed$, $seed$Mein JuBla Highligt ist das Sommerlager, weil man Zeit mit seinen Freunden verbringen kann und mit vielen Erinnerungen zurück kommt.$seed$, $seed$18$seed$, $seed$true$seed$),
  ($seed$levin-kirchhofer$seed$, $seed$Levin Kirchhofer$seed$, $seed$Leve$seed$, $seed$Gruppenleiter 3./4. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/levin-kirchhofer$seed$, $seed$https://media.jubla-triengen.ch/leaders/levin-kirchhofer-background$seed$, $seed$Ich spiele Fussball in Triengen, treffe oft Freunde und bin gerne in der Natur unterwegs.$seed$, $seed$Ich spiele Fussball bei der 1 Mannschaft in Triengen. Auch treffe ich mich oft mit meinen Freunden. Ich bin sehr sportlich und bin gerne in der Natur. Auch in der Fasnachtszeit trifft man mich auf jedem Fall an. Ich bin nämlich in der Guggenmusik Borgguugger Büron.$seed$, $seed$kirchhoferlevin@gmail.ch$seed$, NULL, $seed$September 2008$seed$, $seed$GLK$seed$, $seed$Ressort Bau$seed$, $seed$Lernender Schreiner EFZ Loosli AG Sempach$seed$, $seed$Fussball, Freunde, Natur, Fasnacht, Guggenmusik$seed$, $seed$Das SoLa ist für mich immer das grösste Highlight. Man kann mit seinen Kollegen sehr lustige und abenteuerliche Lager geniessen. Aber auch das Scharmania ist ein Highlight. Das Messen gegen andere JuBla's oder Pfadis macht grossen Spass.$seed$, $seed$19$seed$, $seed$true$seed$),
  ($seed$sandro-luetolf$seed$, $seed$Sandro Lütolf$seed$, $seed$Sänd$seed$, $seed$Gruppenleiter 1./2. Sek Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/sandro-luetolf$seed$, $seed$https://media.jubla-triengen.ch/leaders/sandro-luetolf-background$seed$, $seed$Ich unternehme gerne etwas mit Freunden und Familie, angle gerne und realisiere kreative Ideen.$seed$, $seed$Sehr gerne unternehme ich etwas mit Freunden und Familie. Angeln macht mir grosse Freude, und in der JuBla habe ich mit den Kindern immer viel Spass. Ausserdem Werke ich gerne und realisiere kreative Ideen.$seed$, $seed$sandrowin@hotmail.ch$seed$, NULL, $seed$Juli 2004$seed$, $seed$GLK$seed$, $seed$Ressort Bau & Material, Material Chef$seed$, $seed$Sanitarinstallateur EFZ bei Fellmann Stefan AG$seed$, $seed$Freunde und Familie, Angeln, Werken, Kreative Ideen$seed$, $seed$Jubla Lager. Ich freue mich immer wieder aufs Lager, weil man dort zwei Wochen Spiel und Spass erlebt.$seed$, $seed$20$seed$, $seed$true$seed$),
  ($seed$livio-mueller$seed$, $seed$Livio Müller$seed$, $seed$BJ (Boldy Junior)$seed$, $seed$Gruppenleiter 1./2. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/livio-mueller$seed$, $seed$https://media.jubla-triengen.ch/leaders/livio-mueller-background$seed$, $seed$In meiner Freizeit spiele ich Tennis, fahre Velo, gehe im Winter Ski und unternehme gerne etwas mit Kollegen.$seed$, $seed$In meiner Freizeit spiele ich Tennis, fahre gerne Velo, im Winter Ski und unternehme gerne ab und zu etwas mit Kollegen.$seed$, $seed$livio.mueller77@gmail.com$seed$, NULL, $seed$Januar 2006$seed$, $seed$GLK$seed$, $seed$Ressort Lager$seed$, $seed$Lernender Polymechaniker EFZ bei Reidentechnik AG$seed$, $seed$Tennis, Velo, Ski, Zeit mit Kollegen$seed$, $seed$Mein Jubla Highlight ist das Lager, da man zwei Wochen lang mit der ganzen JuBla eine gute Zeit haben kann. Es gibt immer genug Programm, sodass es niemandem langweilig wird. Es ist immer eine gute Stimmung vorhanden, auch bei schlechtem Wetter.$seed$, $seed$21$seed$, $seed$true$seed$),
  ($seed$cyrill-schmid$seed$, $seed$Cyrill Schmid$seed$, $seed$Cytsch$seed$, $seed$Gruppenleiter 5./6. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/cyrill-schmid$seed$, $seed$https://media.jubla-triengen.ch/leaders/cyrill-schmid-background$seed$, $seed$In meiner Freizeit spiele ich gerne Volleyball und unternehme viel mit Freunden.$seed$, $seed$In meiner Freizeit spiele ich gerne Volleyball oder ich unternehme was was mit Freunden. Ich bin auch gerne draussen in der mit der JuBla.$seed$, $seed$Schmidcyrill44@gmail.com$seed$, NULL, $seed$August 2008$seed$, $seed$GLK$seed$, $seed$Ressort Bau & Material$seed$, $seed$Lernender Koch EFZ im Restaurant iheimisch in Sursee$seed$, $seed$Volleyball, Freunde, Draussen sein$seed$, $seed$Ein JuBla Highlight für mich waren die Gruppenstunde am Samstag, da ich mit Freunden etwas unternehmen konnte. Das jährliche JuBla-Lager war auch ein grosses Highlight für mich das man 2 Wochen in der Natur ist und Spass hat.$seed$, $seed$22$seed$, $seed$true$seed$),
  ($seed$noah-schmid$seed$, $seed$Noah Schmid$seed$, $seed$-$seed$, $seed$Gruppenleiter 3./4. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/noah-schmid$seed$, $seed$https://media.jubla-triengen.ch/leaders/noah-schmid-background$seed$, $seed$In meiner Freizeit bin ich gerne in der JuBla, spiele Volleyball im VBC Triengen und unternehme Sachen mit meinen Freunden.$seed$, $seed$In meiner Freizeit bin ich gerne in der JuBla, spiele Volleyball im VBC Triengen und unternehme Sachen mit meinen Freunden.$seed$, $seed$noahschmid@gmail.com$seed$, NULL, $seed$November 2009$seed$, $seed$-$seed$, $seed$Ressort Lager$seed$, $seed$Lernender Kaufmann EFZ bei Kantonalbank Luzern$seed$, $seed$JuBla, Volleyball, Zeit mit Freunden$seed$, $seed$Mein JuBla Highlight sind die zwei Wochen Sommerlager, weil man dort mit seinen Freunden viele unvergessliche Abenteuer erlebt.$seed$, $seed$23$seed$, $seed$true$seed$),
  ($seed$antonia-stofer$seed$, $seed$Antonia Stofer$seed$, $seed$-$seed$, $seed$Gruppenleiterin 1./2. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/antonia-stofer$seed$, $seed$https://media.jubla-triengen.ch/leaders/antonia-stofer-background$seed$, $seed$In meiner Freizeit spiele ich Volleyball im VBC Triengen und treffe mich gerne mit Kolleginnen.$seed$, $seed$In meiner Freizeit spiele ich im VBC Triengen Volleyball. Ansonsten treffe ich mich gerne mit Kolleginnen um etwas zu unternehmen.$seed$, $seed$antoniastofer@bluewin.ch$seed$, NULL, $seed$Juli 2009$seed$, $seed$-$seed$, $seed$Ressort Kommunikation & Informatik$seed$, $seed$Lernende Kauffrau EFZ bei der Gemeinde Oberkirch, Berufsbegleitende Berufsmatura$seed$, $seed$Volleyball, Zeit mit Kolleginnen$seed$, $seed$Mein JuBla Highlight ist das Lager. Man ist zwei Wochen weg und kann vieles mit seinen Freunden erleben. Man hat viele lustige Momente zusammen, welche unvergesslich sind.$seed$, $seed$24$seed$, $seed$true$seed$),
  ($seed$livia-stofer$seed$, $seed$Livia Stofer$seed$, $seed$-$seed$, $seed$Gruppenleiterin 5./6. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/livia-stofer$seed$, $seed$https://media.jubla-triengen.ch/leaders/livia-stofer-background$seed$, $seed$Ich verbringe gerne Zeit mit Menschen in der JuBla, bin oft im Mühlehof Triengen und gehe im Winter gerne auf die Piste.$seed$, $seed$Ich verbringe gerne Zeit mit verschiedenen Menschen in der JuBla. Ebenfalls bin ich sehr gerne im Mühlehof in Triengen am Reiten und helfen. In den kalten Jahreszeiten findet man mich auch zwischendurch auf den Skipisten.$seed$, $seed$livia_stofer@outlook.com$seed$, NULL, $seed$August 2007$seed$, $seed$GLK$seed$, $seed$Ressort Lager$seed$, $seed$Lernende Medizinische Praxisassistentin bei Dr. med. Ulrich Harte$seed$, $seed$JuBla, Reiten, Helfen im Mühlehof, Skifahren$seed$, $seed$Das Sommerlager ist natürlich jedes Jahr ein Highlight. Man erlebt viele unvergessliche Momente, besonders die Zeit am Lagerfeuer mit singen, lachen und viel Spass bleibt in guter Erinnerung.$seed$, $seed$25$seed$, $seed$true$seed$),
  ($seed$rahel-stofer$seed$, $seed$Rahel Stofer$seed$, $seed$Raschi$seed$, $seed$Gruppenleiterin 1./2. Sek Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/rahel-stofer$seed$, $seed$https://media.jubla-triengen.ch/leaders/rahel-stofer-background$seed$, $seed$Neben der JuBla spiele ich Volleyball im Damenteam vom VBC Triengen und treffe am Wochenende Freunde.$seed$, $seed$Neben der JuBla spiele ich Volleyball im Damenteam vom VBC Triengen. Am Wochenende treffe ich mich gerne mit Freunde für einen unterhaltsamen Abend.$seed$, $seed$rahel-stofer@bluewin.ch$seed$, $seed$079 129 85 30$seed$, $seed$November 2005$seed$, $seed$GLK, SLRG$seed$, $seed$Scharleitung$seed$, $seed$Mediamatikerin beim GO-IN Sportshop Sursee$seed$, $seed$Volleyball, Zeit mit Freunden$seed$, $seed$Mein JuBla Highlight war das Sommerlager 2021 mit dem Thema JuBlasa. Es war für mich das letzte Lager, welches ich als Kind dabei war. Das Wetter war nicht immer super, jedoch konnten wir trotzdem viele lustige Momente miteinander verbringen.$seed$, $seed$26$seed$, $seed$true$seed$),
  ($seed$corsin-troxler$seed$, $seed$Corsin Troxler$seed$, $seed$-$seed$, $seed$Gruppenleiter 3./4. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/corsin-troxler$seed$, $seed$https://media.jubla-triengen.ch/leaders/corsin-troxler-background$seed$, $seed$In meiner Freizeit spiele ich Unihockey in Schlierbach und unternehme gerne etwas mit meinen Kollegen.$seed$, $seed$In meiner Freizeit spiele ich Unihockey in Schlierbach. Ausserdem mache ich gerne etwas mit meinen Kollegen.$seed$, $seed$corsin.troxler@icloud.com$seed$, NULL, $seed$März 2010$seed$, $seed$-$seed$, $seed$Ressort Lager$seed$, $seed$Lernender Elektroinstallateur bei der CKW Triengen$seed$, $seed$Unihockey, Zeit mit Kollegen$seed$, $seed$Mein Mein JuBla Highlight ist das alljährliche Sommerlager. Ich liebe es zwei Wochen auf dem Zeltplatz zu verbringen und jeden Tag etwas spannendes zu unternehmen.$seed$, $seed$27$seed$, $seed$true$seed$),
  ($seed$diego-troxler$seed$, $seed$Diego Troxler$seed$, $seed$Digi$seed$, $seed$Gruppenleiter 3./4. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/diego-troxler$seed$, $seed$https://media.jubla-triengen.ch/leaders/diego-troxler-background$seed$, $seed$Neben der JuBla verbringe ich gerne Zeit mit Familie und Freunden, spiele Unihockey und gehe im Winter Skifahren.$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit auch gerne mit meiner Familie und Freunden. Ich spiele Unihockey und im Winter gehe gerne Skifahren.$seed$, $seed$diego.troxler@bluewin.ch$seed$, $seed$079 844 28 08$seed$, $seed$September 2006$seed$, $seed$GLK$seed$, $seed$Scharleitung$seed$, $seed$Zusatzlehre Elektroinstallateur EFZ bei der Forster AG$seed$, $seed$Familie, Freunde, Unihockey, Skifahren$seed$, $seed$Mein JuBla Highlight ist immer das Lager, weil man es mit den Kindern, Kollegen und Leiter lustig hat, zusammen spielt und einfach eine tolle Zeit hat, die immer in Erinnerung bleiben wird. Natürlich auch die verschiedenen Anlässe, an denen man mit den Kindern etwas tolles erleben kann.$seed$, $seed$28$seed$, $seed$true$seed$),
  ($seed$colin-tschopp$seed$, $seed$Colin Tschopp$seed$, $seed$-$seed$, $seed$Gruppenleiter 1./2. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/colin-tschopp$seed$, $seed$https://media.jubla-triengen.ch/leaders/colin-tschopp-background$seed$, $seed$Ich gehe oft Skifahren, gehe mit dem TV Triengen an Turnfeste und unternehme viel mit Freunden.$seed$, $seed$Ich gehe oft Skifahren. Auch gehe ich gerne mit dem TV Triengen an die Turnfeste. Und unternehme viel mit Freunden.$seed$, $seed$colin.tschopp@bluewin.ch$seed$, NULL, $seed$Januar 2009$seed$, $seed$-$seed$, $seed$Ressort Lager$seed$, $seed$Elektroinstallateur EFZ bei Forster AG$seed$, $seed$Skifahren, Turnfeste, Freunde$seed$, $seed$Das Sommerlager ist mein Highlight, weil das Zusammensein mit den anderen Jublaner*innen sehr lustig ist. Auch die Games die man spielt, machen sehr viel Spass und das Küchen Team kann super kochen!$seed$, $seed$29$seed$, $seed$true$seed$),
  ($seed$jan-utiger$seed$, $seed$Jan Utiger$seed$, $seed$Uti$seed$, $seed$Gruppenleiter 5./6. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/jan-utiger$seed$, $seed$https://media.jubla-triengen.ch/leaders/jan-utiger-background$seed$, $seed$In meiner Freizeit spiele ich gerne Gitarre, verbringe Zeit mit Freunden und bin im Jungschützenverein tätig.$seed$, $seed$In meiner Freizeit spiele ich gerne Gitarre und verbringe gerne Zeit mit meinen Freunden. Zudem bin ich im Jungschützenverein tätig.$seed$, $seed$jan@philipputiger.ch$seed$, NULL, $seed$September 2004$seed$, $seed$GLK$seed$, $seed$Ressort Lager$seed$, $seed$Student an der Universität Zürich, Wirtschaftschemie$seed$, $seed$Gitarre, Freunde, Jungschützenverein$seed$, $seed$Die Bock-Tour ist mein absolutes Highlight. Hierbei kann man sein Wissen über die Pioniertechnik ausleben und hat eine schöne Zeit mit den anderen Leitern.$seed$, $seed$30$seed$, $seed$true$seed$),
  ($seed$nils-utiger$seed$, $seed$Nils Utiger$seed$, $seed$Chli Uti$seed$, $seed$Gruppenleiter 3./4. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/nils-utiger$seed$, $seed$https://media.jubla-triengen.ch/leaders/nils-utiger-background$seed$, $seed$Ich spiele oft Tennis, bin sehr technikbegeistert und beschäftige mich in meiner Freizeit viel damit.$seed$, $seed$Ich spiele in meiner Freizeit oftmals Tennis. Ich bin sehr Technikbegeistert und befasse mich in meiner Freizeit oft damit.$seed$, $seed$nils@philipputiger.ch$seed$, NULL, $seed$Mai 2008$seed$, $seed$GLK$seed$, $seed$Ressort Kom. & Inf.$seed$, $seed$Lernender Informatiker EFZ bei Suva, BM3+$seed$, $seed$Tennis, Technik$seed$, $seed$Jedes Jahr aufs neue ein spektakuläres Rückzelt zu gestalten.$seed$, $seed$31$seed$, $seed$true$seed$),
  ($seed$jonas-wilhelm$seed$, $seed$Jonas Wilhelm$seed$, $seed$Tschouns$seed$, $seed$Gruppenleiter 1./2. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/jonas-wilhelm$seed$, $seed$https://media.jubla-triengen.ch/leaders/jonas-wilhelm-background$seed$, $seed$In meiner Freizeit gehe ich ins Geräteturnen und bin gerne in der Natur.$seed$, $seed$In meiner Freizeit gehe ich ins Geräteturnen und in der Natur.$seed$, $seed$jonas.w2629@gmail.com$seed$, NULL, $seed$Februar 2009$seed$, $seed$-$seed$, $seed$Ressort Bau$seed$, $seed$Lernender Maurer EFZ bei Waller AG Büron$seed$, $seed$Geräteturnen, Natur$seed$, $seed$Ich freue mich jedes Jahr auf das Sommerlager.$seed$, $seed$32$seed$, $seed$true$seed$),
  ($seed$lea-wilhelm$seed$, $seed$Lea Wilhelm$seed$, $seed$Lele$seed$, $seed$Gruppenleiterin 1./2. Sek Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/lea-wilhelm$seed$, $seed$https://media.jubla-triengen.ch/leaders/lea-wilhelm-background$seed$, $seed$Ich bin im Turnverein Triengen und im Geräteturnen, gestalte und male gerne und fahre im Winter Ski und Board.$seed$, $seed$Ich bin im Turnverein Triengen und im Geräteturnen. Gestalten und malen gehören zu meinen Hobbys. Im Winter fahre ich Ski und Board.$seed$, $seed$lea.wilhelm@gmx.ch$seed$, NULL, $seed$Dezember 2005$seed$, $seed$GLK$seed$, $seed$Ressort Kreativ$seed$, $seed$Gestalterin Werbetechnik bei Herby Print Werbe GmbH$seed$, $seed$Turnverein, Geräteturnen, Gestalten, Malen, Ski, Snowboard$seed$, $seed$Meine JuBla Highlights sind die Lager, weil ich da immer lustige, tolle, abenteuerliche, schöne, lehrreiche und einfach unvergessliche Momente erleben darf.$seed$, $seed$33$seed$, $seed$true$seed$),
  ($seed$rafael-wilhelm$seed$, $seed$Rafael Wilhelm$seed$, $seed$Rafi$seed$, $seed$Gruppenleiter 5./6. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/rafael-wilhelm$seed$, $seed$https://media.jubla-triengen.ch/leaders/rafael-wilhelm-background$seed$, $seed$In meiner Freizeit treibe ich viel Sport, bin im Turnverein Triengen aktiv und gehe gerne biken oder skifahren.$seed$, $seed$In meiner Freizeit treibe ich viel Sport. Das ganze Jahr über bin ich aktiv im Turnverein Triengen, im Sommer gehe ich gerne biken und im Winter mache ich die Skipisten unsicher. Am Wochenende stecke ich gerne Zeit in die JuBla, um den Kindern auch solch großartige Erlebnisse zu schenken, wie ich sie in der JuBla erleben durfte.$seed$, $seed$raf.wilhelm@gmail.com$seed$, NULL, $seed$August 2007$seed$, $seed$GLK$seed$, $seed$Ressort Lager$seed$, $seed$Konstrukteur EFZ bei der Trisa AG, Berufsbegleitende Berufsmatura$seed$, $seed$Sport, Turnverein, Biken, Skifahren, JuBla$seed$, $seed$Die Lager sind und waren schon immer meine Highlights. Man ist viel draussen, darf schmutzig werden und spielt coole Games miteinander. Dazu lernt man vieles über das Zelten, Kartenlesen und auch ein bisschen über Erste Hilfe leisten.$seed$, $seed$34$seed$, $seed$true$seed$),
  ($seed$elias-wyss$seed$, $seed$Elias Wyss$seed$, $seed$Ele$seed$, $seed$Gruppenleiter 1./2. Sek Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/elias-wyss$seed$, $seed$https://media.jubla-triengen.ch/leaders/elias-wyss-background$seed$, $seed$In meiner Freizeit bin ich gerne in der JuBla, helfe zu Hause auf dem Bauernhof und verbringe die Wochenenden mit Freunden.$seed$, $seed$In meiner Freizeit bin ich gerne in der JuBla und freue mich auf die Gruppenstunden und das Lager. Oft helfe ich nach der Arbeit zu Hause auf dem Bauernhof mit. Das Wochenende verbringe ich mit meinen Freunden und vielen lustigen Momenten.$seed$, $seed$eliaswyss04@gmail.com$seed$, NULL, $seed$August 2006$seed$, $seed$GLK, SLRG$seed$, $seed$Teamleiter Bau & Material$seed$, $seed$Elektroinstallateur bei der Forster AG$seed$, $seed$JuBla, Bauernhof, Zeit mit Freunden$seed$, $seed$Jedes JuBla Lager ist das Highlight vom Jahr. Jährlich haben wir viele schöne, lustige und abenteuerreiche Momente. Die verschiedenen kreativen Games im Lager mag ich besonders gerne.$seed$, $seed$35$seed$, $seed$true$seed$),
  ($seed$flurin-wyss$seed$, $seed$Flurin Wyss$seed$, $seed$Flöru$seed$, $seed$Gruppenleiter 1./2. Klasse Jungs$seed$, $seed$https://media.jubla-triengen.ch/leaders/flurin-wyss$seed$, $seed$https://media.jubla-triengen.ch/leaders/flurin-wyss-background$seed$, $seed$In meiner Freizeit spiele ich Volleyball im VBC Triengen und unternehme gerne etwas mit meinen Kollegen.$seed$, $seed$In meiner Freizeit spiele ich Volleyball im VBC Triengen. Ich gehe auch gerne mit meinen Kollegen raus und unternehme etwas.$seed$, $seed$flurinwyss125@gmail.com$seed$, NULL, $seed$März 2009$seed$, $seed$-$seed$, $seed$Ressort Bau & Material$seed$, $seed$Lernender Elektroinstallateur bei der CKW Triengen$seed$, $seed$Volleyball, Zeit mit Kollegen$seed$, $seed$Meine Highlights in der JuBla waren immer die coolen Gruppenstunden im Kindergartenwald oder im Hofacker.$seed$, $seed$36$seed$, $seed$true$seed$),
  ($seed$jana-wyss$seed$, $seed$Jana Wyss$seed$, $seed$Tschena$seed$, $seed$Gruppenleiterin 3./4. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/jana-wyss$seed$, $seed$https://media.jubla-triengen.ch/leaders/jana-wyss-background$seed$, $seed$In meiner Freizeit gehe ich in die JuBla und reite gerne; am Wochenende verbringe ich gerne Zeit mit Freunden und Familie.$seed$, $seed$In meiner Freizeit gehe ich natürlich in die JuBla. Ein zweites Hobby von mir ist das Reiten. Am Wochenende liebe ich es Zeit mit Freunden oder mit meiner Familie zu verbringen. Ob dies eine aufregende Aktivität ist oder ein gemütlicher Abend, spielt keine Rolle.$seed$, $seed$wyssjana26@gmail.com$seed$, NULL, $seed$November 2007$seed$, $seed$GLK$seed$, $seed$Ressort Kommunikation & Informatik$seed$, $seed$Lernende Mediamatikerin EFZ bei Vogelwarte Sempach$seed$, $seed$JuBla, Reiten, Zeit mit Freunden und Familie$seed$, $seed$Mein Highlight in der JuBla ist auf jeden Fall das Sommerlager. Ich freue mich am Ende vom Lager, immer schon wieder auf das nächste. In diesen zwei Wochen hatte man immer sehr viel Spass und erlebt unvergessliche Momente.$seed$, $seed$37$seed$, $seed$true$seed$),
  ($seed$louisa-wyss$seed$, $seed$Louisa Wyss$seed$, $seed$Lou$seed$, $seed$Gruppenleiterin 1./2. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/louisa-wyss$seed$, $seed$https://media.jubla-triengen.ch/leaders/louisa-wyss-background$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit am liebsten mit Freunden am See und mit meiner Familie.$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit am liebsten mit meinen Freunden am See und meiner Familie. Gerne nehme ich mir auch Zeit um ein gutes Buch zu Lesen.$seed$, $seed$louwy@gmx.ch$seed$, NULL, $seed$November 2006$seed$, $seed$Brevet Basis & Plus Pool, GLK, SLK$seed$, $seed$Ressort Lager, Lagerleitung$seed$, $seed$Praktikantin$seed$, $seed$Freunde, See, Familie, Lesen$seed$, $seed$Wo soll ich da nur anfangen? Es gibt so viele Highlights in der JuBla. Das JuBla-Lager ist allerdings ein ganz besonderes Highlight für mich. Jedes Jahr aufs Neue freue ich mich auf diese beiden Wochen voller Spaß, Abenteuer und Geselligkeit. Vor allem die gemütlichen Abende am Lagerfeuer genieße ich sehr.$seed$, $seed$38$seed$, $seed$true$seed$),
  ($seed$maya-wyss$seed$, $seed$Maya Wyss$seed$, $seed$-$seed$, $seed$Gruppenleiterin 1./2. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/maya-wyss$seed$, $seed$https://media.jubla-triengen.ch/leaders/maya-wyss-background$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit gerne mit Freunden und Familie.$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit gerne mit Freunden und Familie.$seed$, $seed$vrechmaya10@gmail.com$seed$, NULL, $seed$Juni 2010$seed$, $seed$-$seed$, $seed$Ressort Kommunikation & Informatik$seed$, $seed$Schülerin an der Kantonsschule Sursee$seed$, $seed$Zeit mit Freunden und Familie$seed$, $seed$Mein JuBla-Highlight ist auf jeden Fall das Sommerlager, dass ich seit der 2. Klasse besuche. Am meisten gefallen mir die gemeinsamen Stunden am Lagerfeuer. Die gemütliche Stimmung und das Zusammensein.$seed$, $seed$39$seed$, $seed$true$seed$),
  ($seed$sophia-wyss$seed$, $seed$Sophia Wyss$seed$, $seed$-$seed$, $seed$Gruppenleiterin 3./4. Klasse Mädchen$seed$, $seed$https://media.jubla-triengen.ch/leaders/sophia-wyss$seed$, $seed$https://media.jubla-triengen.ch/leaders/sophia-wyss-background$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit gerne mit Freunden und Familie.$seed$, $seed$Neben der JuBla verbringe ich meine Freizeit auch noch gerne mit Freunden und Familie.$seed$, $seed$soefi.wyss@gmail.com$seed$, NULL, $seed$April 2008$seed$, $seed$GLK$seed$, $seed$Ressort Finanzen$seed$, $seed$Lernende Kauffrau EFZ beim Campus Sursee, Berufsbegleitende Berufsmatura$seed$, $seed$Zeit mit Freunden und Familie$seed$, $seed$Mein absolutes Highlight ist das Lager. Jedes Jahr einfach mal zwei Wochen weg und unvergessliche Erinnerungen schaffen. Coole Games, gemütliche Abende am Lagerfeuer oder einfach die tolle Zeit mit den Freunden im Lager geniessen macht alles Spass.$seed$, $seed$40$seed$, $seed$true$seed$),
  ($seed$brigitte-schmid$seed$, $seed$Brigitte Schmid$seed$, $seed$Brige$seed$, $seed$Präses$seed$, $seed$https://media.jubla-triengen.ch/leaders/brigitte-schmid$seed$, $seed$https://media.jubla-triengen.ch/leaders/brigitte-schmid-background$seed$, $seed$In meiner Freizeit bin ich gerne draussen unterwegs und unternehme gerne etwas mit Familie und Freunden.$seed$, $seed$In meiner Freizeit bin ich gerne draussen unterwegs. Egal ob im eigenen Garten, im Wald, in den Bergen oder auf der Skipiste. Gerne unternehme ich etwas mit meiner Familie und Freunden. Und falls es mal regnet macht es mir Spass kreativ zu sein beim Basteln, Backen, Dekorieren…$seed$, $seed$wyssbrigitte@hotmail.com$seed$, NULL, $seed$Juli 1978$seed$, $seed$Präses Kurs$seed$, $seed$Verbindungsperson zu Elternrat, Pastoralraumleitung und Kirchenrat, Lagerköchin$seed$, $seed$Sekretärin bei der Schweizer Paraplegiker Forschung, Primarlehrerin in Erstausbildung$seed$, $seed$Draussen sein, Garten, Wald, Berge, Skipiste, Kreatives$seed$, $seed$Viele… eines der besten Sommerlager mit 10 Tagen Regen, Matsch, und gefühlten 1'000 h "Pösi" spielen im Tipi Zelt – Muotathal lässt grüssen… Bockwägelitour: Ross und Wagen verladen und über 1 Woche nach Hause marschiert – Country Roads auf den Lippen und unter den Füssen… Haus- gegen Zeltlager Fights mit Braveheart Fackel Angriff by night… Und das Wichtigste: bei all dem die besten Freunde fürs Leben gefunden!$seed$, $seed$41$seed$, $seed$true$seed$);

INSERT INTO albums (id, title, image, sort_order) VALUES
  ($seed$summer-2023$seed$, $seed$Summer Camp 2023$seed$, $seed$https://picsum.photos/seed/1/800/600?grayscale$seed$, $seed$1$seed$),
  ($seed$winter-skiing$seed$, $seed$Winter Skiing$seed$, $seed$https://picsum.photos/seed/2/800/600?grayscale$seed$, $seed$2$seed$),
  ($seed$charity-run$seed$, $seed$Charity Run$seed$, $seed$https://picsum.photos/seed/3/800/600?grayscale$seed$, $seed$3$seed$),
  ($seed$forest-adventure$seed$, $seed$Forest Adventure$seed$, $seed$https://picsum.photos/seed/4/800/600?grayscale$seed$, $seed$4$seed$),
  ($seed$city-trip$seed$, $seed$City Trip$seed$, $seed$https://picsum.photos/seed/5/800/600?grayscale$seed$, $seed$5$seed$);

INSERT INTO photos (id, album_id, img, url, height, sort_order) VALUES
  ($seed$summer-2023-0$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20230/600/375?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20230/1200/800$seed$, $seed$375$seed$, $seed$1$seed$),
  ($seed$summer-2023-1$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20231/600/326?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20231/1200/800$seed$, $seed$326$seed$, $seed$2$seed$),
  ($seed$summer-2023-2$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20232/600/473?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20232/1200/800$seed$, $seed$473$seed$, $seed$3$seed$),
  ($seed$summer-2023-3$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20233/600/366?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20233/1200/800$seed$, $seed$366$seed$, $seed$4$seed$),
  ($seed$summer-2023-4$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20234/600/412?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20234/1200/800$seed$, $seed$412$seed$, $seed$5$seed$),
  ($seed$summer-2023-5$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20235/600/307?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20235/1200/800$seed$, $seed$307$seed$, $seed$6$seed$),
  ($seed$summer-2023-6$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20236/600/434?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20236/1200/800$seed$, $seed$434$seed$, $seed$7$seed$),
  ($seed$summer-2023-7$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20237/600/335?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20237/1200/800$seed$, $seed$335$seed$, $seed$8$seed$),
  ($seed$summer-2023-8$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20238/600/562?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20238/1200/800$seed$, $seed$562$seed$, $seed$9$seed$),
  ($seed$summer-2023-9$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-20239/600/598?grayscale$seed$, $seed$https://picsum.photos/seed/summer-20239/1200/800$seed$, $seed$598$seed$, $seed$10$seed$),
  ($seed$summer-2023-10$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-202310/600/555?grayscale$seed$, $seed$https://picsum.photos/seed/summer-202310/1200/800$seed$, $seed$555$seed$, $seed$11$seed$),
  ($seed$summer-2023-11$seed$, $seed$summer-2023$seed$, $seed$https://picsum.photos/seed/summer-202311/600/449?grayscale$seed$, $seed$https://picsum.photos/seed/summer-202311/1200/800$seed$, $seed$449$seed$, $seed$12$seed$),
  ($seed$winter-skiing-0$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing0/600/492?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing0/1200/800$seed$, $seed$492$seed$, $seed$1$seed$),
  ($seed$winter-skiing-1$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing1/600/558?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing1/1200/800$seed$, $seed$558$seed$, $seed$2$seed$),
  ($seed$winter-skiing-2$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing2/600/478?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing2/1200/800$seed$, $seed$478$seed$, $seed$3$seed$),
  ($seed$winter-skiing-3$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing3/600/327?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing3/1200/800$seed$, $seed$327$seed$, $seed$4$seed$),
  ($seed$winter-skiing-4$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing4/600/342?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing4/1200/800$seed$, $seed$342$seed$, $seed$5$seed$),
  ($seed$winter-skiing-5$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing5/600/585?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing5/1200/800$seed$, $seed$585$seed$, $seed$6$seed$),
  ($seed$winter-skiing-6$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing6/600/577?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing6/1200/800$seed$, $seed$577$seed$, $seed$7$seed$),
  ($seed$winter-skiing-7$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing7/600/566?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing7/1200/800$seed$, $seed$566$seed$, $seed$8$seed$),
  ($seed$winter-skiing-8$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing8/600/465?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing8/1200/800$seed$, $seed$465$seed$, $seed$9$seed$),
  ($seed$winter-skiing-9$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing9/600/354?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing9/1200/800$seed$, $seed$354$seed$, $seed$10$seed$),
  ($seed$winter-skiing-10$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing10/600/465?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing10/1200/800$seed$, $seed$465$seed$, $seed$11$seed$),
  ($seed$winter-skiing-11$seed$, $seed$winter-skiing$seed$, $seed$https://picsum.photos/seed/winter-skiing11/600/377?grayscale$seed$, $seed$https://picsum.photos/seed/winter-skiing11/1200/800$seed$, $seed$377$seed$, $seed$12$seed$),
  ($seed$charity-run-0$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run0/600/582?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run0/1200/800$seed$, $seed$582$seed$, $seed$1$seed$),
  ($seed$charity-run-1$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run1/600/546?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run1/1200/800$seed$, $seed$546$seed$, $seed$2$seed$),
  ($seed$charity-run-2$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run2/600/346?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run2/1200/800$seed$, $seed$346$seed$, $seed$3$seed$),
  ($seed$charity-run-3$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run3/600/548?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run3/1200/800$seed$, $seed$548$seed$, $seed$4$seed$),
  ($seed$charity-run-4$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run4/600/440?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run4/1200/800$seed$, $seed$440$seed$, $seed$5$seed$),
  ($seed$charity-run-5$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run5/600/318?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run5/1200/800$seed$, $seed$318$seed$, $seed$6$seed$),
  ($seed$charity-run-6$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run6/600/306?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run6/1200/800$seed$, $seed$306$seed$, $seed$7$seed$),
  ($seed$charity-run-7$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run7/600/461?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run7/1200/800$seed$, $seed$461$seed$, $seed$8$seed$),
  ($seed$charity-run-8$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run8/600/548?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run8/1200/800$seed$, $seed$548$seed$, $seed$9$seed$),
  ($seed$charity-run-9$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run9/600/553?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run9/1200/800$seed$, $seed$553$seed$, $seed$10$seed$),
  ($seed$charity-run-10$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run10/600/504?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run10/1200/800$seed$, $seed$504$seed$, $seed$11$seed$),
  ($seed$charity-run-11$seed$, $seed$charity-run$seed$, $seed$https://picsum.photos/seed/charity-run11/600/414?grayscale$seed$, $seed$https://picsum.photos/seed/charity-run11/1200/800$seed$, $seed$414$seed$, $seed$12$seed$),
  ($seed$forest-adventure-0$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure0/600/475?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure0/1200/800$seed$, $seed$475$seed$, $seed$1$seed$),
  ($seed$forest-adventure-1$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure1/600/508?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure1/1200/800$seed$, $seed$508$seed$, $seed$2$seed$),
  ($seed$forest-adventure-2$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure2/600/513?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure2/1200/800$seed$, $seed$513$seed$, $seed$3$seed$),
  ($seed$forest-adventure-3$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure3/600/515?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure3/1200/800$seed$, $seed$515$seed$, $seed$4$seed$),
  ($seed$forest-adventure-4$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure4/600/597?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure4/1200/800$seed$, $seed$597$seed$, $seed$5$seed$),
  ($seed$forest-adventure-5$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure5/600/434?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure5/1200/800$seed$, $seed$434$seed$, $seed$6$seed$),
  ($seed$forest-adventure-6$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure6/600/329?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure6/1200/800$seed$, $seed$329$seed$, $seed$7$seed$),
  ($seed$forest-adventure-7$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure7/600/357?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure7/1200/800$seed$, $seed$357$seed$, $seed$8$seed$),
  ($seed$forest-adventure-8$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure8/600/434?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure8/1200/800$seed$, $seed$434$seed$, $seed$9$seed$),
  ($seed$forest-adventure-9$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure9/600/338?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure9/1200/800$seed$, $seed$338$seed$, $seed$10$seed$),
  ($seed$forest-adventure-10$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure10/600/530?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure10/1200/800$seed$, $seed$530$seed$, $seed$11$seed$),
  ($seed$forest-adventure-11$seed$, $seed$forest-adventure$seed$, $seed$https://picsum.photos/seed/forest-adventure11/600/478?grayscale$seed$, $seed$https://picsum.photos/seed/forest-adventure11/1200/800$seed$, $seed$478$seed$, $seed$12$seed$),
  ($seed$city-trip-0$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip0/600/541?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip0/1200/800$seed$, $seed$541$seed$, $seed$1$seed$),
  ($seed$city-trip-1$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip1/600/416?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip1/1200/800$seed$, $seed$416$seed$, $seed$2$seed$),
  ($seed$city-trip-2$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip2/600/364?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip2/1200/800$seed$, $seed$364$seed$, $seed$3$seed$),
  ($seed$city-trip-3$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip3/600/381?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip3/1200/800$seed$, $seed$381$seed$, $seed$4$seed$),
  ($seed$city-trip-4$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip4/600/305?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip4/1200/800$seed$, $seed$305$seed$, $seed$5$seed$),
  ($seed$city-trip-5$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip5/600/383?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip5/1200/800$seed$, $seed$383$seed$, $seed$6$seed$),
  ($seed$city-trip-6$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip6/600/400?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip6/1200/800$seed$, $seed$400$seed$, $seed$7$seed$),
  ($seed$city-trip-7$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip7/600/564?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip7/1200/800$seed$, $seed$564$seed$, $seed$8$seed$),
  ($seed$city-trip-8$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip8/600/586?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip8/1200/800$seed$, $seed$586$seed$, $seed$9$seed$),
  ($seed$city-trip-9$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip9/600/357?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip9/1200/800$seed$, $seed$357$seed$, $seed$10$seed$),
  ($seed$city-trip-10$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip10/600/561?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip10/1200/800$seed$, $seed$561$seed$, $seed$11$seed$),
  ($seed$city-trip-11$seed$, $seed$city-trip$seed$, $seed$https://picsum.photos/seed/city-trip11/600/474?grayscale$seed$, $seed$https://picsum.photos/seed/city-trip11/1200/800$seed$, $seed$474$seed$, $seed$12$seed$);

INSERT INTO legal_sections (page_key, title, content, sort_order) VALUES
  ($seed$impressum$seed$, $seed$Kontaktadresse$seed$, $seed$["Jungwacht Blauring Triengen","Musterstrasse 1","6234 Triengen","Schweiz","E-Mail: info@jubla-triengen.ch"]$seed$::jsonb, 1),
  ($seed$impressum$seed$, $seed$Vertretungsberechtigte Personen$seed$, $seed$["Vorname Nachname, Scharleitung","Vorname Nachname, Scharleitung"]$seed$::jsonb, 2),
  ($seed$impressum$seed$, $seed$Haftungsausschluss$seed$, $seed$["Der Autor übernimmt keinerlei Gewähr hinsichtlich der inhaltlichen Richtigkeit, Genauigkeit, Aktualität, Zuverlässigkeit und Vollständigkeit der Informationen. Haftungsansprüche gegen den Autor wegen Schäden materieller oder immaterieller Art, welche aus dem Zugriff oder der Nutzung bzw. Nichtnutzung der veröffentlichten Informationen, durch Missbrauch der Verbindung oder durch technische Störungen entstanden sind, werden ausgeschlossen.","Alle Angebote sind unverbindlich. Der Autor behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen."]$seed$::jsonb, 3),
  ($seed$impressum$seed$, $seed$Haftung für Links$seed$, $seed$["Verweise und Links auf Webseiten Dritter liegen ausserhalb unseres Verantwortungsbereichs. Es wird jegliche Verantwortung für solche Webseiten abgelehnt. Der Zugriff und die Nutzung solcher Webseiten erfolgen auf eigene Gefahr des Nutzers oder der Nutzerin."]$seed$::jsonb, 4),
  ($seed$impressum$seed$, $seed$Urheberrechte$seed$, $seed$["Die Urheber- und alle anderen Rechte an Inhalten, Bildern, Fotos oder anderen Dateien auf der Website gehören ausschliesslich der Jungwacht Blauring Triengen oder den speziell genannten Rechtsinhabern. Für die Reproduktion jeglicher Elemente ist die schriftliche Zustimmung der Urheberrechtsträger im Voraus einzuholen."]$seed$::jsonb, 5),
  ($seed$data_protection$seed$, NULL, $seed$["Verantwortliche Stelle im Sinne der Datenschutzgesetze, insbesondere der EU-Datenschutzgrundverordnung (DSGVO), ist:","Jungwacht Blauring Triengen","Musterstrasse 1","6234 Triengen","E-Mail: info@jubla-triengen.ch","Webseite: https://www.jubla-triengen.ch/"]$seed$::jsonb, 1),
  ($seed$data_protection$seed$, $seed$Allgemeiner Hinweis$seed$, $seed$["Gestützt auf Artikel 13 der schweizerischen Bundesverfassung und die datenschutzrechtlichen Bestimmungen des Bundes (Datenschutzgesetz, DSG) hat jede Person Anspruch auf Schutz ihrer Privatsphäre sowie auf Schutz vor Missbrauch ihrer persönlichen Daten. Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung."]$seed$::jsonb, 2),
  ($seed$data_protection$seed$, $seed$Datenerfassung auf unserer Website$seed$, $seed$["Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.","Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich."]$seed$::jsonb, 3),
  ($seed$data_protection$seed$, $seed$Cookies$seed$, $seed$["Diese Website verwendet Cookies. Cookies sind kleine Textdateien, die beim Besuch dieser Website in Ihrem Computer dauerhaft oder temporär gespeichert werden. Zweck der Cookies ist insbesondere die Analyse der Nutzung dieser Website zur statistischen Auswertung sowie für kontinuierliche Verbesserungen. In Ihrem Browser können Sie Cookies in den Einstellungen jederzeit ganz oder teilweise deaktivieren. Bei deaktivierten Cookies stehen Ihnen allenfalls nicht mehr alle Funktionen dieser Website zur Verfügung."]$seed$::jsonb, 4),
  ($seed$data_protection$seed$, $seed$Kontaktformular$seed$, $seed$["Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben aus dem Anfrageformular inklusive der von Ihnen dort angegebenen Kontaktdaten zwecks Bearbeitung der Anfrage und für den Fall von Anschlussfragen bei uns gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter."]$seed$::jsonb, 5);

INSERT INTO navigation_items (location, label, href, icon, sort_order) VALUES
  ($seed$header$seed$, $seed$Über uns$seed$, $seed$/über-uns$seed$, NULL, 1),
  ($seed$header$seed$, $seed$Angebote$seed$, $seed$/angebote$seed$, NULL, 2),
  ($seed$header$seed$, $seed$Anlässe$seed$, $seed$/anlässe$seed$, NULL, 3),
  ($seed$header$seed$, $seed$Neues aus der Jubla$seed$, $seed$/posts$seed$, NULL, 4),
  ($seed$footer_contact$seed$, $seed$info@jubla-triengen.ch$seed$, $seed$mailto:info@jubla-triengen.ch$seed$, $seed$mail$seed$, 1),
  ($seed$footer_contact$seed$, $seed$+41 41 123 45 67$seed$, $seed$tel:+41411234567$seed$, $seed$phone$seed$, 2),
  ($seed$footer_contact$seed$, $seed$Triengen, Luzern$seed$, NULL, $seed$map-pin$seed$, 3),
  ($seed$footer_links$seed$, $seed$Angebote$seed$, $seed$/angebote$seed$, NULL, 1),
  ($seed$footer_links$seed$, $seed$Anlässe$seed$, $seed$/anlässe$seed$, NULL, 2),
  ($seed$footer_links$seed$, $seed$News$seed$, $seed$/posts$seed$, NULL, 3),
  ($seed$footer_links$seed$, $seed$Über uns$seed$, $seed$/über-uns$seed$, NULL, 4),
  ($seed$footer_social$seed$, $seed$Facebook$seed$, $seed$https://www.facebook.com/jublatriengen$seed$, $seed$facebook$seed$, 1),
  ($seed$footer_social$seed$, $seed$Instagram$seed$, $seed$https://www.instagram.com/jublatriengen/$seed$, $seed$instagram$seed$, 2),
  ($seed$footer_legal$seed$, $seed$Datenschutz$seed$, $seed$/datenschutz$seed$, NULL, 1),
  ($seed$footer_legal$seed$, $seed$Impressum$seed$, $seed$/impressum$seed$, NULL, 2);

INSERT INTO site_settings (key, value) VALUES
  ($seed$brand$seed$, $seed${"name":"Jubla Triengen","description":"Abenteuer, Freundschaft und unvergessliche Erlebnisse für Kinder und Jugendliche."}$seed$::jsonb),
  ($seed$header_cta$seed$, $seed${"label":"Mitmachen","href":"/kontakt"}$seed$::jsonb);

COMMIT;
